default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 186dd18042ad30269e157e17db271a34b71e3bcd # v4.8.4
    hooks:
      - id: commitizen
        stages:
          - commit-msg
      - id: commitizen-branch
        stages:
          - pre-push
